[package]
name = "snake_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
peg = "0.7.0"
regex = "1.5.4"
lazy_static = "1.4.0"
thiserror = "1.0.30"
crossterm = "0.22.1"