a = 1 // comment

{
    a = 2
}
//

// comment

a = {
    print(a)
    b = 3 + 3

    c = {
        d = "d"
        d
    }
    
    c
}

a = {
    if(0) {
        print("true")
        "true"
    }
    else {
        print("false")
        "false"
    }
}

a = 10
while(a) {
    a = a - 1
    print(a)
}

fn my_print(a) {
    print(a)
}

my_print("my print")

fn sum(a, b) {
    {
        c = 1
        a + b
    }
}

a = 1
b = 1
print("a =", a)
print("b =", b)
print('a + b =', sum(a, b))

print(sum)

mem()